// LOCALHOST ### 
GET http://localhost:8080/contacts 
### Get contact by id 
GET http://localhost:8080/contacts/6487c9877ae4b456bc010b61
### Get contact by id 
GET http://localhost:8080/contacts/6487c9dc7ae4b456bc010b62
### Get contact by id 
GET http://localhost:8080/contacts/6487ca0b7ae4b456bc010b63

### Create contact 
POST http://localhost:8080/contacts HTTP/1.1 
content-type: application/json

{
    "firstName":"Jesus", 
    "lastName":"Ramirez", 
    "email":"jesusramirez@gmail.com", 
    "favoriteColor":"Brown", 
    "birthday":"1/5/1999"
}

### PUT contact 
PUT http://localhost:8080/contacts/648957623b6f5ebdce9caffa HTTP/1.1 
content-type: application/json

{
"firstName":"Jesus", 
"lastName":"Ramirez", 
"email":"jesusramirez@hotmail.com", 
"favoriteColor":"Green", 
"birthday":"1/5/1999"
} 
### DELETE contact 
DELETE http://localhost:8080/contacts/648957623b6f5ebdce9caffa HTTP/1.1

// RENDER ##
###
GET https://cse341-personal-project2.onrender.com/contacts
### Get contact by id 
GET https://cse341-personal-project2.onrender.com/contacts/6487c9877ae4b456bc010b61
### Get contact by id 
GET https://cse341-personal-project2.onrender.com/contacts/6487c9dc7ae4b456bc010b62
### Get contact by id 
GET https://cse341-personal-project2.onrender.com/contacts/6487ca0b7ae4b456bc010b63

### Create contact 
POST https://cse341-personal-project2.onrender.com/contacts HTTP/1.1 
content-type: application/json

{
    "firstName":"Jesus", 
    "lastName":"Ramirez", 
    "email":"jesusramirez@gmail.com", 
    "favoriteColor":"Brown", 
    "birthday":"1/5/1999"
}

### PUT contact 
PUT https://cse341-personal-project2.onrender.com/contacts/648957c846eb15a1fc61e9d0 HTTP/1.1 
content-type: application/json

{
"firstName":"Jesus", 
"lastName":"Ramirez", 
"email":"jesusramirez@hotmail.com", 
"favoriteColor":"Green", 
"birthday":"1/5/1999"
} 
### DELETE contact 
DELETE https://cse341-personal-project2.onrender.com/contacts/648957c846eb15a1fc61e9d0 HTTP/1.1